"""empty message

Revision ID: 15ddd697d3f4
Revises: 43c875c0b1e0
Create Date: 2021-08-14 21:00:09.146542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ddd697d3f4'
down_revision = '43c875c0b1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('trans_time', sa.String(length=65), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'trans_time')
    # ### end Alembic commands ###
