"""empty message

Revision ID: 47fa2a144d63
Revises: 7b742df0063d
Create Date: 2021-09-06 13:15:35.403040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fa2a144d63'
down_revision = '7b742df0063d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CheckoutRequestID', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payment_accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stk_CheckoutRequestID'), 'stk', ['CheckoutRequestID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stk_CheckoutRequestID'), table_name='stk')
    op.drop_table('stk')
    # ### end Alembic commands ###
