"""empty message

Revision ID: 933e0f1ca6a6
Revises: ce0930b8d3ea
Create Date: 2021-08-13 13:22:26.524025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933e0f1ca6a6'
down_revision = 'ce0930b8d3ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=65), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_commands_name'), 'bot_commands', ['name'], unique=True)
    op.create_table('bot_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['bot_commands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_activity')
    op.drop_index(op.f('ix_bot_commands_name'), table_name='bot_commands')
    op.drop_table('bot_commands')
    # ### end Alembic commands ###
